<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();
$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^20\d{2}-\d{2}$/',$month))$month=date('Y-m');
$start=$month.'-01';$dt=new DateTimeImmutable($start);$end=$dt->modify('last day of this month')->format('Y-m-d');$prev=$dt->modify('-1 month')->format('Y-m');$next=$dt->modify('+1 month')->format('Y-m');
$st=$pdo->prepare("SELECT 'jogo' tipo,j.IdJogo id,j.DataJogo data,j.HoraJogo hora,CONCAT(e.NomeEquipa,' vs ',j.Adversario) titulo,COALESCE(j.Local,'') local,j.EstadoJogo estado FROM jogos j LEFT JOIN equipas e ON e.IdEquipa=j.IdEquipa WHERE j.DataJogo BETWEEN ? AND ? UNION ALL SELECT 'treino',t.IdTreino,t.DataTreino,t.HoraInicio,CONCAT('Treino · ',e.NomeEquipa,' · ',t.TipoTreino),COALESCE(t.Local,''),'Treino' FROM treinos t LEFT JOIN equipas e ON e.IdEquipa=t.IdEquipa WHERE t.DataTreino BETWEEN ? AND ? ORDER BY data,hora");$st->execute([$start,$end,$start,$end]);$items=$st->fetchAll();
$byDate=[];foreach($items as $i)$byDate[$i['data']][]=$i;
render_header('Calendário','calendario');
?>
<div class="page-head"><div><h1>Calendário</h1><p>Jogos e treinos num único planeamento mensal.</p></div><div class="actions"><a class="btn" href="?month=<?=$prev?>">← Mês anterior</a><span class="btn primary"><?=h($dt->format('m/Y'))?></span><a class="btn" href="?month=<?=$next?>">Mês seguinte →</a></div></div>
<section class="panel"><div class="calendar-grid calendar-head"><div>Seg</div><div>Ter</div><div>Qua</div><div>Qui</div><div>Sex</div><div>Sáb</div><div>Dom</div></div><div class="calendar-grid month-grid">
<?php $firstDow=(int)$dt->format('N');for($x=1;$x<$firstDow;$x++):?><div class="calendar-day muted-day"></div><?php endfor;?>
<?php for($d=1;$d<=(int)$dt->format('t');$d++):$date=$dt->format('Y-m-').str_pad((string)$d,2,'0',STR_PAD_LEFT);?><div class="calendar-day <?=$date===date('Y-m-d')?'today':''?>"><div class="day-number"><?=$d?></div><?php foreach($byDate[$date]??[] as $it):$url=$it['tipo']==='jogo'?'jogo.php?id='.$it['id']:'treinos.php';?><a class="cal-item <?=$it['tipo']?>" href="<?=h($url)?>"><strong><?=h(substr((string)($it['hora']??''),0,5))?></strong><span><?=h($it['titulo'])?></span></a><?php endforeach;?></div><?php endfor;?></div></section>
<section class="panel" style="margin-top:14px"><div class="panel-head"><div class="panel-title"><span class="accent">◫</span>Agenda do mês</div><span class="chip"><?=count($items)?> eventos</span></div><div class="panel-body table-wrap"><?php if(!$items):?><div class="empty"><strong>Sem eventos este mês</strong>Adiciona jogos ou treinos.</div><?php else:?><table><thead><tr><th>Data</th><th>Tipo</th><th>Evento</th><th>Local</th><th>Estado</th></tr></thead><tbody><?php foreach($items as $it):?><tr data-searchable><td><?=h(db_datetime($it['data'],$it['hora']))?></td><td><span class="chip"><?=h($it['tipo'])?></span></td><td><?=h($it['titulo'])?></td><td><?=h($it['local']?:'—')?></td><td><span class="status <?=h(status_class($it['estado']))?>"><?=h($it['estado'])?></span></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section>
<?php render_footer();?>
