<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();$id=(int)($_GET['id']??0);$st=$pdo->prepare("SELECT * FROM competicoes WHERE IdCompeticao=?");$st->execute([$id]);$c=$st->fetch();if(!$c){http_response_code(404);exit('Competição não encontrada.');}
$games=[];$st=$pdo->prepare("SELECT j.*,e.NomeEquipa FROM jogos j LEFT JOIN equipas e ON e.IdEquipa=j.IdEquipa WHERE j.IdCompeticao=? ORDER BY j.DataJogo,j.HoraJogo");$st->execute([$id]);$games=$st->fetchAll();
$teams=[];if(table_exists('competicoes_equipas')){$st=$pdo->prepare("SELECT ce.*,e.NomeEquipa,e.Genero FROM competicoes_equipas ce JOIN equipas e ON e.IdEquipa=ce.IdEquipa WHERE ce.IdCompeticao=? ORDER BY e.NomeEquipa");$st->execute([$id]);$teams=$st->fetchAll();}
$class=[];if(table_exists('classificacao_competicao')){$st=$pdo->prepare("SELECT cl.*,e.NomeEquipa FROM classificacao_competicao cl JOIN equipas e ON e.IdEquipa=cl.IdEquipa WHERE cl.IdCompeticao=? ORDER BY cl.Posicao,cl.Pontos DESC");$st->execute([$id]);$class=$st->fetchAll();}
render_header($c['NomeCompeticao'],'competicoes');
?>
<div class="profile-hero"><div class="team-crest-large">★</div><div class="profile-main"><div class="eyebrow"><?=h($c['CodigoFPA']??'Competição')?></div><h1><?=h($c['NomeCompeticao'])?></h1><div class="profile-tags"><span class="chip"><?=h($c['Epoca'])?></span><?php if(!empty($c['Genero'])):?><span class="chip"><?=h($c['Genero'])?></span><?php endif;?><?php if(!empty($c['Escalao'])):?><span class="chip"><?=h($c['Escalao'])?></span><?php endif;?></div></div><div class="actions"><a class="btn" href="competicoes.php">← Competições</a><a class="btn" href="participacoes.php?filter[IdCompeticao]=<?=$id?>">Participações</a><a class="btn" href="classificacoes.php?filter[IdCompeticao]=<?=$id?>">Classificação</a><?php if(!empty($c['FonteURL'])):?><a class="btn" target="_blank" rel="noopener" href="<?=h($c['FonteURL'])?>">Fonte oficial ↗</a><?php endif;?><?php if(can_manage()):?><a class="btn primary" href="competicoes.php?edit=<?=$id?>#form">Editar</a><?php endif;?></div></div>
<?php if(!empty($c['Formato'])):?><section class="panel info-banner"><div class="panel-body"><strong>Formato da prova</strong><p><?=nl2br(h($c['Formato']))?></p></div></section><?php endif;?>
<div class="grid2 profile-grid"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">◎</span>Equipas participantes</div><span class="chip"><?=count($teams)?> equipas</span></div><div class="panel-body roster-cards"><?php if(!$teams):?><div class="empty"><strong>Sem participantes associados</strong>Usa o módulo de competição/equipas depois do upgrade.</div><?php else:?><?php foreach($teams as $t):?><a class="player-card" href="equipa.php?id=<?=$t['IdEquipa']?>"><span class="crest"><?=h(initials($t['NomeEquipa']))?></span><div><strong><?=h($t['NomeEquipa'])?></strong><small><?=h($t['Genero'])?></small></div><span class="status"><?=h($t['Estado']??'Ativa')?></span></a><?php endforeach;?><?php endif;?></div></section>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▥</span>Classificação</div></div><div class="panel-body table-wrap"><?php if(!$class):?><div class="empty"><strong>Classificação ainda não carregada</strong>Podes importar/editar a classificação na base de dados sem alterar os jogos internos.</div><?php else:?><table><thead><tr><th>#</th><th>Equipa</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GM</th><th>GS</th><th>DG</th><th>Pts</th></tr></thead><tbody><?php foreach($class as $r):?><tr><td><strong><?=h($r['Posicao'])?></strong></td><td><?=h($r['NomeEquipa'])?></td><td><?=h($r['Jogos'])?></td><td><?=h($r['Vitorias'])?></td><td><?=h($r['Empates'])?></td><td><?=h($r['Derrotas'])?></td><td><?=h($r['GolosMarcados'])?></td><td><?=h($r['GolosSofridos'])?></td><td><?=h($r['DiferencaGolos'])?></td><td><strong><?=h($r['Pontos'])?></strong></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section></div>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▤</span>Jogos registados no HandManager</div><span class="chip"><?=count($games)?> jogos</span></div><div class="panel-body table-wrap"><?php if(!$games):?><div class="empty"><strong>Sem jogos internos</strong>Os jogos da tua equipa aparecerão aqui quando associados à competição.</div><?php else:?><table><thead><tr><th>Data</th><th>Equipa</th><th>Adversário</th><th>Jornada</th><th>Resultado</th><th>Estado</th></tr></thead><tbody><?php foreach($games as $g):?><tr><td><?=h(db_datetime($g['DataJogo'],$g['HoraJogo']))?></td><td><?=h($g['NomeEquipa'])?></td><td><a class="text-link" href="jogo.php?id=<?=$g['IdJogo']?>"><?=h($g['Adversario'])?></a></td><td><?=h($g['Jornada']??'—')?></td><td><?=h(($g['GolosFavor']??'—').' - '.($g['GolosContra']??'—'))?></td><td><span class="status <?=h(status_class($g['EstadoJogo']))?>"><?=h($g['EstadoJogo'])?></span></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section>
<?php render_footer();?>
