<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT * FROM equipas WHERE IdEquipa=?");$st->execute([$id]);$e=$st->fetch();if(!$e){http_response_code(404);exit('Equipa não encontrada.');}
$ath=[];$st=$pdo->prepare("SELECT a.* FROM atletas a WHERE a.IdEquipa=? ORDER BY a.Posicao='GR' DESC,a.NumeroCamisola IS NULL,a.NumeroCamisola,a.Nome");$st->execute([$id]);$ath=$st->fetchAll();
$staff=[];if(table_exists('treinadores')){$st=$pdo->prepare("SELECT * FROM treinadores WHERE IdEquipa=? AND Estado='Ativo' ORDER BY FIELD(Cargo,'Treinador Principal','Treinador Adjunto','Treinador de Guarda-Redes','Preparador Físico','Fisioterapeuta','Fisio Terapeuta'),Nome");$st->execute([$id]);$staff=$st->fetchAll();}
$games=[];$st=$pdo->prepare("SELECT j.*,c.NomeCompeticao FROM jogos j LEFT JOIN competicoes c ON c.IdCompeticao=j.IdCompeticao WHERE j.IdEquipa=? ORDER BY j.DataJogo DESC,j.HoraJogo DESC LIMIT 12");$st->execute([$id]);$games=$st->fetchAll();
$next=[];$st=$pdo->prepare("SELECT * FROM jogos WHERE IdEquipa=? AND DataJogo>=CURDATE() AND EstadoJogo IN ('Agendado','Adiado') ORDER BY DataJogo,HoraJogo LIMIT 5");$st->execute([$id]);$next=$st->fetchAll();
$training=[];$st=$pdo->prepare("SELECT * FROM treinos WHERE IdEquipa=? ORDER BY DataTreino DESC,HoraInicio DESC LIMIT 5");$st->execute([$id]);$training=$st->fetchAll();
$done=array_filter($games,fn($g)=>$g['EstadoJogo']==='Realizado');$wins=count(array_filter($done,fn($g)=>(int)$g['GolosFavor']>(int)$g['GolosContra']));$draws=count(array_filter($done,fn($g)=>(int)$g['GolosFavor']===(int)$g['GolosContra']));$losses=count($done)-$wins-$draws;$gf=array_sum(array_map(fn($g)=>(int)($g['GolosFavor']??0),$done));$gc=array_sum(array_map(fn($g)=>(int)($g['GolosContra']??0),$done));
render_header($e['NomeEquipa'],'equipas');
?>
<div class="profile-hero team-hero"><div class="team-crest-large"><?=h(initials($e['NomeEquipa']))?></div><div class="profile-main"><div class="eyebrow">Ficha de equipa</div><h1><?=h($e['NomeEquipa'])?></h1><div class="profile-tags"><span class="status <?=h(status_class($e['EstadoEquipa']))?>"><?=h($e['EstadoEquipa'])?></span><span class="chip"><?=h($e['Genero'])?></span><span class="chip"><?=h($e['Escalao'])?></span><span class="chip"><?=h($e['Epoca'])?></span></div></div><div class="actions"><a class="btn" href="equipas.php">← Equipas</a><?php if(can_manage()):?><a class="btn primary" href="equipas.php?edit=<?=$id?>#form">Editar</a><?php endif;?></div></div>
<div class="kpis profile-kpis"><div class="kpi"><div><div class="kpi-label">Plantel</div><div class="kpi-value"><?=count($ath)?></div><div class="kpi-sub">atletas associados</div></div></div><div class="kpi"><div><div class="kpi-label">Jogos realizados</div><div class="kpi-value"><?=count($done)?></div><div class="kpi-sub"><?=$wins?> V · <?=$draws?> E · <?=$losses?> D</div></div></div><div class="kpi"><div><div class="kpi-label">Golos</div><div class="kpi-value small-value"><?=$gf?> / <?=$gc?></div><div class="kpi-sub">marcados / sofridos</div></div></div><div class="kpi"><div><div class="kpi-label">Treinador</div><div class="kpi-value tiny-value"><?=h($e['Treinador']??($staff[0]['Nome']??'—'))?></div><div class="kpi-sub"><?=h($e['Pavilhao']??'Pavilhão não definido')?></div></div></div></div>
<div class="grid2 profile-grid">
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">♟</span>Plantel</div><a class="panel-link" href="atletas.php?filter[IdEquipa]=<?=$id?>">Ver todos →</a></div><div class="panel-body roster-cards"><?php if(!$ath):?><div class="empty"><strong>Sem atletas</strong>Associa atletas a esta equipa.</div><?php else:?><?php foreach($ath as $a):?><a class="player-card" href="atleta.php?id=<?=$a['IdAtleta']?>"><span class="mini-avatar"><?=h(initials($a['Nome']))?></span><div><strong><?=h($a['Nome'])?></strong><small><?=h($a['Posicao']??'—')?> · #<?=h($a['NumeroCamisola']??'—')?></small></div><span class="status <?=h(status_class($a['EstadoDoJogador']))?>"><?=h($a['EstadoDoJogador'])?></span></a><?php endforeach;?><?php endif;?></div></section>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">♜</span>Equipa técnica</div><a class="panel-link" href="treinadores.php?filter[IdEquipa]=<?=$id?>">Gerir →</a></div><div class="panel-body"><?php if(!$staff):?><div class="empty"><strong>Sem staff registado</strong>Adiciona treinadores e equipa técnica.</div><?php else:?><div class="timeline"><?php foreach($staff as $s):?><div class="timeline-item"><i></i><div><strong><?=h($s['Nome'])?></strong><span><?=h($s['Cargo'])?> · <?=h($s['Epoca'])?></span></div><span class="status"><?=h($s['Estado'])?></span></div><?php endforeach;?></div><?php endif;?></div></section>
</div>
<div class="grid2 profile-grid">
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▤</span>Jogos recentes</div><a class="panel-link" href="jogos.php?filter[IdEquipa]=<?=$id?>">Jogos →</a></div><div class="panel-body table-wrap"><?php if(!$games):?><div class="empty"><strong>Sem jogos</strong>Não existem jogos associados.</div><?php else:?><table><thead><tr><th>Data</th><th>Adversário</th><th>Competição</th><th>Resultado</th><th>Estado</th></tr></thead><tbody><?php foreach($games as $g):?><tr><td><?=h(db_date($g['DataJogo']))?></td><td><a class="text-link" href="jogo.php?id=<?=$g['IdJogo']?>"><?=h($g['Adversario'])?></a></td><td><?=h($g['NomeCompeticao']??'—')?></td><td><?=h(($g['GolosFavor']??'—').' - '.($g['GolosContra']??'—'))?></td><td><span class="status <?=h(status_class($g['EstadoJogo']))?>"><?=h($g['EstadoJogo'])?></span></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">◫</span>Próxima atividade</div></div><div class="panel-body"><?php if(!$next&&!$training):?><div class="empty"><strong>Agenda vazia</strong>Adiciona jogos ou treinos.</div><?php endif;?><?php foreach($next as $g):?><a class="agenda-row" href="jogo.php?id=<?=$g['IdJogo']?>"><span class="agenda-date"><?=h(date('d M',strtotime($g['DataJogo'])))?></span><div><strong>vs <?=h($g['Adversario'])?></strong><small><?=h(substr((string)$g['HoraJogo'],0,5))?> · <?=h($g['Local']??'local por definir')?></small></div><span class="chip">Jogo</span></a><?php endforeach;?><?php foreach($training as $t):?><div class="agenda-row"><span class="agenda-date"><?=h(date('d M',strtotime($t['DataTreino'])))?></span><div><strong><?=h($t['TipoTreino'])?></strong><small><?=h(substr((string)$t['HoraInicio'],0,5))?> · <?=h($t['Local']??'local por definir')?></small></div><span class="chip">Treino</span></div><?php endforeach;?></div></section>
</div>
<?php render_footer();?>
