<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();
$team=(int)($_GET['equipa']??0);$teams=$pdo->query("SELECT IdEquipa,NomeEquipa FROM equipas ORDER BY NomeEquipa")->fetchAll();
$whereTeam=$team?" AND a.IdEquipa=".$team:'';
$goals=(int)$pdo->query("SELECT COUNT(*) FROM eventos_jogo ev JOIN atletas a ON a.IdAtleta=ev.IdAtleta WHERE ev.TipoEvento IN ('Golo','Golo 7m') $whereTeam")->fetchColumn();
$assists=(int)$pdo->query("SELECT COUNT(*) FROM eventos_jogo ev JOIN atletas a ON a.IdAtleta=ev.IdAtleta WHERE ev.TipoEvento='Assistencia' $whereTeam")->fetchColumn();
$shots=(int)$pdo->query("SELECT COUNT(*) FROM eventos_jogo ev JOIN atletas a ON a.IdAtleta=ev.IdAtleta WHERE ev.TipoEvento IN ('Golo','Remate','Remate Falhado','Remate Defendido','Remate ao Poste','Golo 7m','7m Falhado','7m Defendido') $whereTeam")->fetchColumn();
$saves=(int)$pdo->query("SELECT COUNT(*) FROM eventos_jogo ev JOIN atletas a ON a.IdAtleta=ev.IdAtleta WHERE ev.TipoEvento IN ('Defesa','Defesa 7m') $whereTeam")->fetchColumn();$eff=pct($goals,$shots,1);
$top=[];$keepers=[];try{$sql="SELECT v.*,e.NomeEquipa FROM vw_eficiencia_atletas v LEFT JOIN atletas a ON a.IdAtleta=v.IdAtleta LEFT JOIN equipas e ON e.IdEquipa=a.IdEquipa WHERE 1=1".($team?" AND a.IdEquipa=".$team:'')." ORDER BY v.Golos DESC,v.Assistencias DESC,v.Nome";$top=$pdo->query($sql)->fetchAll();$keepers=array_values(array_filter($top,fn($r)=>(int)($r['RematesEnfrentados']??0)>0));usort($keepers,fn($a,$b)=>(float)$b['EficaciaGuardaRedes']<=>(float)$a['EficaciaGuardaRedes']);}catch(Throwable){}
$byGame=$pdo->query("SELECT DATE_FORMAT(DataJogo,'%d/%m') label,COALESCE(GolosFavor,0) value FROM jogos WHERE EstadoJogo='Realizado'".($team?" AND IdEquipa=".$team:'')." ORDER BY DataJogo DESC LIMIT 10")->fetchAll();$byGame=array_reverse($byGame);
render_header('Estatísticas','estatisticas');?>
<div class="page-head"><div><h1>Estatísticas & performance</h1><p>Indicadores calculados automaticamente a partir dos eventos registados.</p></div><form class="actions" method="get"><select name="equipa" class="season" onchange="this.form.submit()"><option value="0">Todas as equipas</option><?php foreach($teams as $t):?><option value="<?=$t['IdEquipa']?>" <?=$team===(int)$t['IdEquipa']?'selected':''?>><?=h($t['NomeEquipa'])?></option><?php endforeach;?></select></form></div>
<div class="stat-strip"><div class="stat-mini"><span>Golos</span><strong><?=$goals?></strong></div><div class="stat-mini"><span>Assistências</span><strong><?=$assists?></strong></div><div class="stat-mini"><span>Eficácia de remate</span><strong><?=$eff?>%</strong></div><div class="stat-mini"><span>Defesas</span><strong><?=$saves?></strong></div></div>
<div class="grid2 profile-grid"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▥</span>Golos por jogo</div></div><div class="panel-body"><div class="chart"><canvas id="statsChart"></canvas></div></div></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">◎</span>Indicadores</div></div><div class="panel-body"><div class="metric-list"><div><span>Finalizações</span><b><?=$shots?></b></div><div><span>Golos</span><b><?=$goals?></b></div><div><span>Assistências</span><b><?=$assists?></b></div><div><span>Eficácia global</span><b><?=$eff?>%</b></div></div><div class="source-note compact-note"><strong>Regra de cálculo</strong><span>Cada finalização deve ser registada uma única vez pelo resultado: golo, falhado, defendido, poste ou 7 metros.</span></div></div></section></div>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">♟</span>Desempenho individual</div><span class="chip"><?=count($top)?> atletas</span></div><div class="panel-body table-wrap"><?php if(!$top):?><div class="empty"><strong>Sem estatísticas</strong>Adiciona eventos de jogo para gerar os indicadores.</div><?php else:?><table><thead><tr><th>Atleta</th><th>Equipa</th><th>Pos.</th><th>Jogos</th><th>Golos</th><th>Remates</th><th>Eficácia</th><th>7m</th><th>Assist.</th><th>Recup.</th><th>Perdas</th></tr></thead><tbody><?php foreach($top as $r):?><tr data-searchable><td><a class="person text-link" href="atleta.php?id=<?=$r['IdAtleta']?>"><span class="mini-avatar"><?=h(initials($r['Nome']))?></span><?=h($r['Nome'])?></a></td><td><?=h($r['NomeEquipa']??'—')?></td><td><?=h($r['Posicao']??'—')?></td><td><?=h($r['JogosComRegisto'])?></td><td><strong><?=h($r['Golos'])?></strong></td><td><?=h($r['Remates'])?></td><td><?=h($r['EficaciaRemate']??0)?>%</td><td><?=h(($r['Golos7m']??0).'/'.($r['Remates7m']??0))?></td><td><?=h($r['Assistencias'])?></td><td><?=h($r['Recuperacoes'])?></td><td><?=h($r['PerdasBola'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section>
<section class="panel" style="margin-top:14px"><div class="panel-head"><div class="panel-title"><span class="accent">🧤</span>Guarda-redes</div></div><div class="panel-body table-wrap"><?php if(!$keepers):?><div class="empty"><strong>Sem dados de guarda-redes</strong>Regista defesas e golos sofridos.</div><?php else:?><table><thead><tr><th>#</th><th>Guarda-redes</th><th>Equipa</th><th>Defesas</th><th>Defesas 7m</th><th>Golos sofridos</th><th>Remates enfrentados</th><th>Eficácia</th></tr></thead><tbody><?php foreach(array_slice($keepers,0,25) as $i=>$r):?><tr><td><?=$i+1?></td><td><a class="text-link" href="atleta.php?id=<?=$r['IdAtleta']?>"><?=h($r['Nome'])?></a></td><td><?=h($r['NomeEquipa']??'—')?></td><td><?=h($r['Defesas'])?></td><td><?=h($r['Defesas7m'])?></td><td><?=h($r['GolosSofridos'])?></td><td><?=h($r['RematesEnfrentados'])?></td><td><strong><?=h($r['EficaciaGuardaRedes'])?>%</strong></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section>
<script>window.HM_STATS=<?=json_encode($byGame,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><?php render_footer();?>
