<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();
$sources=[];if(table_exists('fontes_externas'))$sources=$pdo->query("SELECT * FROM fontes_externas WHERE Ativa=1 ORDER BY Prioridade,Nome")->fetchAll();
$masc=['ABC de Braga Lusíadas Saúde','AD Carvalhos','Águas Santas Milaneza','Avanca Bioria Bondalti','CF Os Belenenses','FC Porto','GC Santo Tirso','Marítimo Madeira Andebol SAD','Póvoa AC Bodegão CCR Proteu','SL Benfica','Sporting CP','Vitória SC'];
$fem=['ABC de Braga OBO Bettermann','ADA São Pedro do Sul','Alavarium ACA','CA Leça','CD Feirense','CDE Gil Eanes','CJ Almeida Garrett Pristivus','Juve Lis','Madeira SAD','SL Benfica'];
render_header('Fontes externas','fontes');?>
<div class="page-head"><div><h1>Fontes externas</h1><p>Referências oficiais e públicas usadas para validar estrutura competitiva e dados federativos.</p></div></div>
<div class="source-note"><strong>Política de dados</strong><span>O HandManager mantém os dados operacionais na tua base MySQL. FPA e zerozero são referências de validação; alterações externas não sobrescrevem automaticamente os teus registos.</span></div>
<div class="cards source-cards"><?php if($sources):foreach($sources as $s):?><a class="card source-card" target="_blank" rel="noopener" href="<?=h($s['URL'])?>"><div class="source-logo"><?=h(initials($s['Nome']))?></div><div><h3><?=h($s['Nome'])?></h3><p><?=h($s['Descricao']??'Fonte pública de informação de andebol.')?></p><div class="card-meta"><span class="chip"><?=h($s['Tipo'])?></span><span class="chip">Abrir ↗</span></div></div></a><?php endforeach;else:?><a class="card source-card" target="_blank" rel="noopener" href="https://portal.fpa.pt/"><div class="source-logo">FPA</div><div><h3>Federação de Andebol de Portugal</h3><p>Regulamentos, calendários, competições e documentação oficial.</p></div></a><a class="card source-card" target="_blank" rel="noopener" href="https://www.zerozero.pt/modalidade/andebol/5"><div class="source-logo">ZZ</div><div><h3>zerozero Andebol</h3><p>Calendários, resultados, equipas e estatísticas públicas.</p></div></a><?php endif;?></div>
<div class="grid2 profile-grid"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">♂</span>Campeonato Betclic Masculino 2026/27</div><span class="chip">12 equipas</span></div><div class="panel-body roster-cards"><?php foreach($masc as $n):?><div class="player-card"><span class="crest"><?=h(initials($n))?></span><div><strong><?=h($n)?></strong><small>Seniores A Masculino</small></div></div><?php endforeach;?></div></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">♀</span>Campeonato Betclic Feminino 2026/27</div><span class="chip">10 equipas</span></div><div class="panel-body roster-cards"><?php foreach($fem as $n):?><div class="player-card"><span class="crest"><?=h(initials($n))?></span><div><strong><?=h($n)?></strong><small>Seniores A Feminino</small></div></div><?php endforeach;?></div></section></div>
<section class="panel info-banner"><div class="panel-body"><strong>Época 2026/2027</strong><p>As duas principais competições nacionais usam a designação Campeonato Betclic Masculino e Campeonato Betclic Feminino. A fase inicial arrancou a 29 de agosto de 2026. O módulo de competições do HandManager foi preparado para guardar código FPA, género, formato e fonte oficial.</p></div></section>
<?php render_footer();?>
