<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/layout.php';require_login();$pdo=db();$season=current_season();
$athletes=table_count('atletas');$teams=table_count('equipas');$gamesDone=(int)$pdo->query("SELECT COUNT(*) FROM jogos WHERE EstadoJogo='Realizado'")->fetchColumn();$trainings=table_count('treinos');
$wins=(int)$pdo->query("SELECT COUNT(*) FROM jogos WHERE EstadoJogo='Realizado' AND GolosFavor>GolosContra")->fetchColumn();$winRate=$gamesDone?round($wins/$gamesDone*100):0;
$injuries=table_exists('lesoes')?(int)$pdo->query("SELECT COUNT(*) FROM lesoes WHERE Estado IN ('Em Recuperacao','Indisponivel')")->fetchColumn():0;
$recent=$pdo->query("SELECT IdJogo,DataJogo,GolosFavor,GolosContra FROM jogos WHERE EstadoJogo='Realizado' ORDER BY DataJogo DESC,IdJogo DESC LIMIT 8")->fetchAll();$recent=array_reverse($recent);$chart=array_map(fn($r)=>['label'=>date('d/m',strtotime($r['DataJogo'])),'gf'=>(int)$r['GolosFavor'],'gc'=>(int)$r['GolosContra']],$recent);
$pos=$pdo->query("SELECT COALESCE(Posicao,'Sem posição') label,COUNT(*) value FROM atletas GROUP BY Posicao ORDER BY value DESC")->fetchAll();
$upcoming=$pdo->query("SELECT j.*,e.NomeEquipa,c.NomeCompeticao FROM jogos j LEFT JOIN equipas e ON e.IdEquipa=j.IdEquipa LEFT JOIN competicoes c ON c.IdCompeticao=j.IdCompeticao WHERE j.DataJogo>=CURDATE() AND j.EstadoJogo IN ('Agendado','Adiado') ORDER BY j.DataJogo,j.HoraJogo LIMIT 7")->fetchAll();
$events=$pdo->query("SELECT ev.*,a.Nome,j.Adversario FROM eventos_jogo ev LEFT JOIN atletas a ON a.IdAtleta=ev.IdAtleta LEFT JOIN jogos j ON j.IdJogo=ev.IdJogo ORDER BY ev.IdEvento DESC LIMIT 6")->fetchAll();
$tops=[];try{$tops=$pdo->query("SELECT IdAtleta,Nome,NumeroCamisola,Posicao,Golos,EficaciaRemate FROM vw_eficiencia_atletas WHERE Golos>0 ORDER BY Golos DESC,EficaciaRemate DESC LIMIT 5")->fetchAll();}catch(Throwable){}
$todayTrain=$pdo->query("SELECT t.*,e.NomeEquipa FROM treinos t LEFT JOIN equipas e ON e.IdEquipa=t.IdEquipa WHERE t.DataTreino BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 7 DAY) ORDER BY t.DataTreino,t.HoraInicio LIMIT 6")->fetchAll();
$alerts=[];
if($injuries)$alerts[]=['type'=>'red','title'=>$injuries.' atleta(s) indisponível(eis)','text'=>'Consulta o acompanhamento clínico e datas previstas de regresso.','url'=>'lesoes.php'];
if(!$upcoming)$alerts[]=['type'=>'yellow','title'=>'Sem próximos jogos agendados','text'=>'Adiciona o calendário para alimentar convocatórias e estatísticas.','url'=>'jogos.php?new=1#form'];
$unassigned=(int)$pdo->query("SELECT COUNT(*) FROM atletas WHERE IdEquipa IS NULL")->fetchColumn();if($unassigned)$alerts[]=['type'=>'yellow','title'=>$unassigned.' atleta(s) sem equipa principal','text'=>'Revê as inscrições e associações de plantel.','url'=>'atletas.php?filter[IdEquipa]=__none__'];
$competitions=[];if(column_exists('competicoes','CodigoFPA'))$competitions=$pdo->query("SELECT * FROM competicoes WHERE Epoca=".$pdo->quote($season)." ORDER BY FIELD(CodigoFPA,'PO01','PO09','PO20','PO23'),NomeCompeticao LIMIT 6")->fetchAll();
render_header('Dashboard','dashboard');
?>
<div class="hero dashboard-hero"><div><span class="eyebrow">Época <?=h($season)?></span><h1>Centro de controlo desportivo</h1><p>Plantéis, competição, performance, treino e saúde numa visão única.</p></div><div class="hero-actions"><a class="btn primary" href="jogos.php?new=1#form">+ Novo jogo</a><a class="btn" href="treinos.php?new=1#form">+ Novo treino</a><a class="btn" href="relatorios.php">Relatórios</a></div></div>
<div class="kpis"><div class="kpi"><div class="kpi-ico">♟</div><div><div class="kpi-label">Atletas</div><div class="kpi-value"><?=$athletes?></div><div class="kpi-sub"><?=$teams?> equipas registadas</div></div></div><div class="kpi"><div class="kpi-ico">▣</div><div><div class="kpi-label">Jogos realizados</div><div class="kpi-value"><?=$gamesDone?></div><div class="kpi-sub"><?=$winRate?>% taxa de vitória</div></div></div><div class="kpi green"><div class="kpi-ico">⚒</div><div><div class="kpi-label">Treinos</div><div class="kpi-value"><?=$trainings?></div><div class="kpi-sub">sessões registadas</div></div></div><div class="kpi <?=$injuries?'danger-kpi':'gold'?>"><div class="kpi-ico">✚</div><div><div class="kpi-label">Indisponíveis</div><div class="kpi-value"><?=$injuries?></div><div class="kpi-sub">lesões ativas</div></div></div></div>
<div class="grid3"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▥</span>Performance recente</div><a class="panel-link" href="estatisticas.php">Análise completa →</a></div><div class="panel-body"><div class="chart"><canvas id="performanceChart"></canvas></div></div></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">◔</span>Plantel por posição</div></div><div class="panel-body donut-layout"><div class="donut"><canvas id="positionChart"></canvas><div class="donut-center"><?=$athletes?><small>atletas</small></div></div><div class="legend"><?php $colors=['yellow','','green','violet','red','',''];foreach($pos as $i=>$p):?><div class="legend-row"><i class="dot <?=$colors[$i]??''?>"></i><span><?=h($p['label'])?></span><strong><?=h($p['value'])?></strong></div><?php endforeach;?></div></div></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">!</span>Alertas operacionais</div></div><div class="panel-body alerts"><?php if(!$alerts):?><div class="empty"><strong>Sem alertas críticos</strong>A operação está organizada.</div><?php else:foreach($alerts as $al):?><a class="alert-row <?=$al['type']?>" href="<?=h($al['url'])?>"><b><?=h($al['title'])?></b><span><?=h($al['text'])?></span></a><?php endforeach;endif;?></div></section></div>
<div class="grid-bottom"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▣</span>Próximos jogos</div><a class="panel-link" href="calendario.php">Calendário →</a></div><div class="panel-body table-wrap"><?php if(!$upcoming):?><div class="empty"><strong>Sem jogos agendados</strong>Adiciona um jogo para aparecer aqui.</div><?php else:?><table><thead><tr><th>Data</th><th>Adversário</th><th>Equipa</th><th>Competição</th><th>Estado</th></tr></thead><tbody><?php foreach($upcoming as $j):?><tr data-searchable><td><?=h(db_datetime($j['DataJogo'],$j['HoraJogo']))?></td><td><a class="text-link" href="jogo.php?id=<?=$j['IdJogo']?>"><?=h($j['Adversario'])?></a></td><td><?=h($j['NomeEquipa'])?></td><td><?=h($j['NomeCompeticao']?:'—')?></td><td><span class="status <?=h(status_class($j['EstadoJogo']))?>"><?=h($j['EstadoJogo'])?></span></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">◎</span>Top marcadores</div><a class="panel-link" href="estatisticas.php">Rankings →</a></div><div class="panel-body rank"><?php if(!$tops):?><div class="empty"><strong>Sem golos registados</strong>Os rankings são calculados pelos eventos.</div><?php else:$max=max(1,(int)$tops[0]['Golos']);foreach($tops as $i=>$t):?><a class="rank-item" href="atleta.php?id=<?=$t['IdAtleta']?>"><strong><?=$i+1?></strong><div class="person"><span class="mini-avatar"><?=h(initials($t['Nome']))?></span><div><strong><?=h($t['Nome'])?></strong><div style="color:#819bb2"><?=h($t['Posicao']?:'—')?> · #<?=h($t['NumeroCamisola']?:'—')?></div></div></div><div><strong><?=h($t['Golos'])?></strong><div class="bar"><i style="width:<?=max(4,round($t['Golos']/$max*100))?>%"></i></div></div></a><?php endforeach;endif;?></div></section><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">⚒</span>Próximos treinos</div><a class="panel-link" href="treinos.php">Treinos →</a></div><div class="panel-body"><?php if(!$todayTrain):?><div class="empty"><strong>Sem treinos próximos</strong>Planeia uma nova sessão.</div><?php else:foreach($todayTrain as $t):?><div class="agenda-row"><span class="agenda-date"><?=h(date('d M',strtotime($t['DataTreino'])))?></span><div><strong><?=h($t['NomeEquipa'])?> · <?=h($t['TipoTreino'])?></strong><small><?=h(substr((string)$t['HoraInicio'],0,5))?> · <?=h($t['Local']??'local por definir')?></small></div><a class="chip" href="presencas.php?treino=<?=$t['IdTreino']?>">Presenças</a></div><?php endforeach;endif;?></div></section></div>
<?php if($competitions):?><section class="panel" style="margin-top:14px"><div class="panel-head"><div class="panel-title"><span class="accent">★</span>Competições <?=h($season)?></div><a class="panel-link" href="fontes.php">Fontes FPA / zerozero →</a></div><div class="panel-body cards"><?php foreach($competitions as $c):?><a class="card" href="competicao.php?id=<?=$c['IdCompeticao']?>"><div class="eyebrow"><?=h($c['CodigoFPA']??'')?></div><h3><?=h($c['NomeCompeticao'])?></h3><p><?=h(($c['Genero']??'').' · '.($c['Escalao']??''))?></p></a><?php endforeach;?></div></section><?php endif;?>
<script>window.HM_DASH=<?=json_encode(['games'=>$chart,'positions'=>$pos],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><?php render_footer();?>
