<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT j.*,e.NomeEquipa,c.NomeCompeticao FROM jogos j LEFT JOIN equipas e ON e.IdEquipa=j.IdEquipa LEFT JOIN competicoes c ON c.IdCompeticao=j.IdCompeticao WHERE j.IdJogo=?");$st->execute([$id]);$j=$st->fetch();if(!$j){http_response_code(404);exit('Jogo não encontrado.');}
$conv=[];if(table_exists('convocatorias')){$st=$pdo->prepare("SELECT c.*,a.Nome,a.Posicao,a.NumeroCamisola FROM convocatorias c JOIN atletas a ON a.IdAtleta=c.IdAtleta WHERE c.IdJogo=? ORDER BY c.Titular DESC,a.NumeroCamisola IS NULL,a.NumeroCamisola,a.Nome");$st->execute([$id]);$conv=$st->fetchAll();}
$events=[];if(table_exists('eventos_jogo')){$st=$pdo->prepare("SELECT ev.*,a.Nome,a.NumeroCamisola FROM eventos_jogo ev LEFT JOIN atletas a ON a.IdAtleta=ev.IdAtleta WHERE ev.IdJogo=? ORDER BY COALESCE(ev.Minuto,0),COALESCE(ev.Segundo,0),ev.IdEvento");$st->execute([$id]);$events=$st->fetchAll();}
$stats=[];try{$st=$pdo->prepare("SELECT * FROM vw_estatisticas_atleta_jogo WHERE IdJogo=? ORDER BY Golos DESC,Assistencias DESC,Nome");$st->execute([$id]);$stats=$st->fetchAll();}catch(Throwable){}
render_header('Jogo vs '.$j['Adversario'],'jogos');
?>
<div class="match-hero"><div><span class="eyebrow"><?=h($j['NomeCompeticao']??'Jogo')?></span><h1><?=h($j['NomeEquipa']??'Equipa')?> <b><?=h(($j['GolosFavor']??'–').' : '.($j['GolosContra']??'–'))?></b> <?=h($j['Adversario'])?></h1><p><?=h(db_datetime($j['DataJogo'],$j['HoraJogo']))?> · <?=h($j['Local']??'Local por definir')?> · <?=h($j['CasaFora'])?></p><div class="profile-tags"><span class="status <?=h(status_class($j['EstadoJogo']))?>"><?=h($j['EstadoJogo'])?></span><?php if($j['Jornada']):?><span class="chip">Jornada <?=h($j['Jornada'])?></span><?php endif;?></div></div><div class="actions"><a class="btn" href="jogos.php">← Jogos</a><a class="btn" href="convocatorias.php?jogo=<?=$id?>">Convocatória</a><a class="btn primary" href="eventos.php?jogo=<?=$id?>">Registar eventos</a></div></div>
<div class="grid2 profile-grid"><section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▧</span>Convocatória</div><span class="chip"><?=count($conv)?> atletas</span></div><div class="panel-body roster-cards"><?php if(!$conv):?><div class="empty"><strong>Sem convocatória</strong>Seleciona atletas para este jogo.</div><?php else:?><?php foreach($conv as $c):?><a class="player-card" href="atleta.php?id=<?=$c['IdAtleta']?>"><span class="mini-avatar"><?=h(initials($c['Nome']))?></span><div><strong><?=h($c['Nome'])?></strong><small><?=h($c['Posicao']??'—')?> · #<?=h($c['NumeroCamisola']??'—')?><?=$c['Titular']?' · Titular':''?></small></div><span class="status <?=h(status_class($c['Estado']))?>"><?=h($c['Estado'])?></span></a><?php endforeach;?><?php endif;?></div></section>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">ϟ</span>Linha temporal</div><a class="panel-link" href="eventos.php?jogo=<?=$id?>">Editar →</a></div><div class="panel-body events timeline-events"><?php if(!$events):?><div class="empty"><strong>Sem eventos</strong>Regista o jogo em tempo real.</div><?php else:?><?php foreach($events as $ev):?><div class="event"><div class="event-ico">●</div><div><strong><?=h($ev['Nome']??'Equipa')?></strong><span><?=h($ev['TipoEvento'])?><?=!empty($ev['Observacao'])?' · '.h($ev['Observacao']):''?></span></div><time><?=h(($ev['Minuto']??0)."'".str_pad((string)($ev['Segundo']??0),2,'0',STR_PAD_LEFT))?></time></div><?php endforeach;?><?php endif;?></div></section></div>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">▥</span>Estatísticas individuais</div></div><div class="panel-body table-wrap"><?php if(!$stats):?><div class="empty"><strong>Sem estatísticas</strong>São calculadas automaticamente pelos eventos.</div><?php else:?><table><thead><tr><th>Atleta</th><th>Golos</th><th>Remates</th><th>Eficácia</th><th>Assist.</th><th>Recup.</th><th>Perdas</th><th>Defesas</th><th>Eficácia GR</th></tr></thead><tbody><?php foreach($stats as $s):?><tr><td><a class="text-link" href="atleta.php?id=<?=$s['IdAtleta']?>"><?=h($s['Nome'])?></a></td><td><?=h($s['Golos'])?></td><td><?=h($s['Remates'])?></td><td><?=h($s['EficaciaRemate'])?>%</td><td><?=h($s['Assistencias'])?></td><td><?=h($s['Recuperacoes'])?></td><td><?=h($s['PerdasBola'])?></td><td><?=h($s['Defesas'])?></td><td><?=h($s['EficaciaGuardaRedes'])?>%</td></tr><?php endforeach;?></tbody></table><?php endif;?></div></section>
<?php render_footer();?>
