<?php
declare(strict_types=1);
require_once __DIR__.'/includes/layout.php';require_login();$pdo=db();$u=current_user();
if(!table_exists('notificacoes')){render_header('Notificações','notificacoes');echo '<div class="hero"><h1>Notificações</h1><p>Executa upgrade_2026_2027.sql para ativar este módulo.</p></div>';render_footer();exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';if($action==='read_all'){$st=$pdo->prepare("UPDATE notificacoes SET Lida=1 WHERE IdUtilizador IS NULL OR IdUtilizador=?");$st->execute([$u['id']]);flash('success','Notificações marcadas como lidas.');}elseif($action==='read'){$id=(int)($_POST['id']??0);$st=$pdo->prepare("UPDATE notificacoes SET Lida=1 WHERE IdNotificacao=? AND (IdUtilizador IS NULL OR IdUtilizador=?)");$st->execute([$id,$u['id']]);}redirect('notificacoes.php');}
$st=$pdo->prepare("SELECT * FROM notificacoes WHERE IdUtilizador IS NULL OR IdUtilizador=? ORDER BY Lida ASC,CriadaEm DESC LIMIT 200");$st->execute([$u['id']]);$rows=$st->fetchAll();$unread=count(array_filter($rows,fn($r)=>!$r['Lida']));
render_header('Notificações','notificacoes');?>
<div class="page-head"><div><h1>Notificações</h1><p>Avisos operacionais, sistema e acompanhamento desportivo.</p></div><?php if($unread):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="read_all"><button class="btn">Marcar tudo como lido</button></form><?php endif;?></div>
<section class="panel"><div class="panel-head"><div class="panel-title"><span class="accent">●</span>Centro de notificações</div><span class="chip"><?=$unread?> por ler</span></div><div class="panel-body notification-list"><?php if(!$rows):?><div class="empty"><strong>Sem notificações</strong>Quando houver avisos aparecem aqui.</div><?php else:foreach($rows as $n):?><div class="notification-row <?=$n['Lida']?'read':''?>"><span class="notif-dot <?=h(mb_strtolower($n['Tipo']))?>"></span><div><strong><?=h($n['Titulo'])?></strong><p><?=h($n['Mensagem'])?></p><small><?=h(db_datetime(substr($n['CriadaEm'],0,10),substr($n['CriadaEm'],11,8)))?></small></div><div class="actions"><?php if(!empty($n['Link'])):?><a class="btn small" href="<?=h($n['Link'])?>">Abrir</a><?php endif;?><?php if(!$n['Lida']):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="read"><input type="hidden" name="id" value="<?=$n['IdNotificacao']?>"><button class="btn small">Lida</button></form><?php endif;?></div></div><?php endforeach;endif;?></div></section>
<?php render_footer();?>
