<?php
declare(strict_types=1);

return [
'equipas'=>[
 'table'=>'equipas','pk'=>'IdEquipa','title'=>'Equipas','singular'=>'equipa','subtitle'=>'Clubes, escalões, género, época e enquadramento técnico.','detail'=>'equipa.php?id={id}',
 'filters'=>['NomeEquipa','Escalao','Genero','Epoca','EstadoEquipa'],
 'fields'=>[
  'NomeEquipa'=>['label'=>'Nome da equipa','type'=>'text','required'=>true,'search'=>true],
  'NomeOficial'=>['label'=>'Designação oficial','type'=>'text','search'=>true],
  'Abreviatura'=>['label'=>'Sigla','type'=>'text'],
  'Escalao'=>['label'=>'Escalão','type'=>'select','options'=>['Sub10','Sub12','Sub14','Sub16','Sub18','Sub20','SenioresB','SenioresA'],'required'=>true],
  'Genero'=>['label'=>'Género','type'=>'select','options'=>['Masculino','Feminino','Misto'],'required'=>true],
  'Epoca'=>['label'=>'Época','type'=>'text','required'=>true,'default'=>'2026/2027'],
  'Treinador'=>['label'=>'Treinador principal','type'=>'text','search'=>true],
  'Cidade'=>['label'=>'Cidade','type'=>'text','search'=>true],
  'Pavilhao'=>['label'=>'Pavilhão','type'=>'text','search'=>true],
  'Website'=>['label'=>'Website','type'=>'url'],
  'FonteURL'=>['label'=>'Fonte','type'=>'url'],
  'EstadoEquipa'=>['label'=>'Estado','type'=>'select','options'=>['Ativa','Inativa'],'required'=>true,'default'=>'Ativa'],
 ]],
'atletas'=>[
 'table'=>'atletas','pk'=>'IdAtleta','title'=>'Atletas','singular'=>'atleta','subtitle'=>'Plantel, dados federativos, físicos, posição, inscrição e estado.','detail'=>'atleta.php?id={id}',
 'filters'=>['Nome','CIPA','Sexo','DataNasc','MaoDominante','Escalao','Posicao','EstadoDoJogador','IdEquipa'],
 'fields'=>[
  'CIPA'=>['label'=>'CIPA','type'=>'number','min'=>'1','search'=>true],
  'Nome'=>['label'=>'Nome','type'=>'text','required'=>true,'search'=>true],
  'Sexo'=>['label'=>'Sexo','type'=>'select','options'=>['M','F']],
  'Nacionalidade'=>['label'=>'Nacionalidade','type'=>'text','search'=>true],
  'Foto'=>['label'=>'URL da fotografia','type'=>'url'],
  'DataNasc'=>['label'=>'Data de nascimento','type'=>'date','nullable'=>true],
  'Altura'=>['label'=>'Altura (m)','type'=>'number','step'=>'0.01','min'=>'1','max'=>'2.5'],
  'Peso'=>['label'=>'Peso (kg)','type'=>'number','step'=>'0.01','min'=>'20','max'=>'250'],
  'MaoDominante'=>['label'=>'Mão dominante','type'=>'select','options'=>['Direita','Esquerda','Ambidestro']],
  'Escalao'=>['label'=>'Escalão','type'=>'select','options'=>['Sub10','Sub12','Sub14','Sub16','Sub18','Sub20','SenioresB','SenioresA']],
  'Posicao'=>['label'=>'Posição','type'=>'select','options'=>['GR','P','PE','PD','L','LE','LD','C','PV']],
  'NumeroCamisola'=>['label'=>'N.º camisola','type'=>'number','min'=>'0','max'=>'99'],
  'EstadoDoJogador'=>['label'=>'Estado','type'=>'select','options'=>['Ativo','Inativo','Lesionado','Suspenso'],'required'=>true,'default'=>'Ativo'],
  'IdEquipa'=>['label'=>'Equipa principal','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','nullable'=>true],
  'Fonte'=>['label'=>'Origem dos dados','type'=>'text','search'=>true],
  'Observacoes'=>['label'=>'Observações','type'=>'textarea','full'=>true],
 ]],
'escaloes'=>[
 'table'=>'escaloes','pk'=>'IdEscalao','title'=>'Escalões','singular'=>'escalão','subtitle'=>'Mapa etário e organização competitiva por sexo e época.',
 'filters'=>['Codigo','Sexo','Estado'],
 'fields'=>[
  'Codigo'=>['label'=>'Código','type'=>'text','required'=>true,'search'=>true],
  'Nome'=>['label'=>'Designação','type'=>'text','required'=>true,'search'=>true],
  'Sexo'=>['label'=>'Sexo','type'=>'select','options'=>['M','F'],'required'=>true],
  'AnoNascimentoInicio'=>['label'=>'Ano inicial','type'=>'number'],
  'AnoNascimentoFim'=>['label'=>'Ano final','type'=>'number'],
  'Ordem'=>['label'=>'Ordem','type'=>'number','required'=>true,'default'=>'0'],
  'Estado'=>['label'=>'Estado','type'=>'select','options'=>['Ativo','Inativo'],'required'=>true,'default'=>'Ativo'],
 ]],
'inscricoes'=>[
 'table'=>'inscricoes_atleta','pk'=>'IdInscricao','title'=>'Inscrições','singular'=>'inscrição','subtitle'=>'Relação atleta–equipa–escalão por época, permitindo múltiplas inscrições.',
 'filters'=>['IdAtleta','IdEquipa','IdEscalao','Epoca','Estado'],
 'fields'=>[
  'IdAtleta'=>['label'=>'Atleta','type'=>'relation','table'=>'atletas','pk'=>'IdAtleta','display'=>'Nome','required'=>true],
  'IdEquipa'=>['label'=>'Equipa','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','required'=>true],
  'IdEscalao'=>['label'=>'Escalão','type'=>'relation','table'=>'escaloes','pk'=>'IdEscalao','display'=>'Nome','required'=>true],
  'Epoca'=>['label'=>'Época','type'=>'text','required'=>true,'default'=>'2026/2027'],
  'NumeroCamisola'=>['label'=>'N.º camisola','type'=>'number','min'=>'0','max'=>'99'],
  'Estado'=>['label'=>'Estado','type'=>'select','options'=>['Ativo','Inativo','Suspenso','Lesionado'],'required'=>true,'default'=>'Ativo'],
  'DataInicio'=>['label'=>'Início','type'=>'date'],
  'DataFim'=>['label'=>'Fim','type'=>'date'],
 ]],
'treinadores'=>[
 'table'=>'treinadores','pk'=>'IdTreinador','title'=>'Equipa técnica','singular'=>'elemento técnico','subtitle'=>'Treinadores e staff associados às equipas por época.',
 'filters'=>['Nome','IdEquipa','Cargo','Epoca','Estado'],
 'fields'=>[
  'Nome'=>['label'=>'Nome','type'=>'text','required'=>true,'search'=>true],
  'IdEquipa'=>['label'=>'Equipa','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','required'=>true],
  'Cargo'=>['label'=>'Função','type'=>'select','options'=>['Treinador Principal','Treinador Adjunto','Treinador de Guarda-Redes','Preparador Físico','Fisioterapeuta','Fisio Terapeuta','Analista','Diretor Desportivo'],'required'=>true],
  'Epoca'=>['label'=>'Época','type'=>'text','required'=>true,'default'=>'2026/2027'],
  'Estado'=>['label'=>'Estado','type'=>'select','options'=>['Ativo','Inativo'],'required'=>true,'default'=>'Ativo'],
 ]],
'competicoes'=>[
 'table'=>'competicoes','pk'=>'IdCompeticao','title'=>'Competições','singular'=>'competição','subtitle'=>'Provas nacionais, fases, calendário e enquadramento federativo.','detail'=>'competicao.php?id={id}',
 'filters'=>['NomeCompeticao','Epoca','Escalao','Genero','Organizador'],
 'fields'=>[
  'CodigoFPA'=>['label'=>'Código FPA','type'=>'text','search'=>true],
  'NomeCompeticao'=>['label'=>'Competição','type'=>'text','required'=>true,'search'=>true],
  'Epoca'=>['label'=>'Época','type'=>'text','required'=>true,'default'=>'2026/2027'],
  'Escalao'=>['label'=>'Escalão','type'=>'select','options'=>['Sub10','Sub12','Sub14','Sub16','Sub18','Sub20','SenioresB','SenioresA']],
  'Genero'=>['label'=>'Género','type'=>'select','options'=>['Masculino','Feminino','Misto']],
  'Organizador'=>['label'=>'Organizador','type'=>'text','search'=>true,'default'=>'Federação de Andebol de Portugal'],
  'Formato'=>['label'=>'Formato','type'=>'textarea','full'=>true],
  'DataInicio'=>['label'=>'Início','type'=>'date'],
  'DataFim'=>['label'=>'Fim','type'=>'date'],
  'FonteURL'=>['label'=>'Fonte oficial','type'=>'url'],
 ]],
'jogos'=>[
 'table'=>'jogos','pk'=>'IdJogo','title'=>'Jogos','singular'=>'jogo','subtitle'=>'Calendário, adversários, competição, resultados e contexto do encontro.','detail'=>'jogo.php?id={id}',
 'filters'=>['IdEquipa','IdCompeticao','DataJogo','Adversario','EstadoJogo','CasaFora'],
 'fields'=>[
  'IdEquipa'=>['label'=>'Equipa','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','required'=>true],
  'IdCompeticao'=>['label'=>'Competição','type'=>'relation','table'=>'competicoes','pk'=>'IdCompeticao','display'=>'NomeCompeticao','nullable'=>true],
  'DataJogo'=>['label'=>'Data','type'=>'date','required'=>true],
  'HoraJogo'=>['label'=>'Hora','type'=>'time'],
  'Adversario'=>['label'=>'Adversário','type'=>'text','required'=>true,'search'=>true],
  'Local'=>['label'=>'Local / Pavilhão','type'=>'text','search'=>true],
  'Jornada'=>['label'=>'Jornada','type'=>'number','min'=>'0'],
  'GolosFavor'=>['label'=>'Golos a favor','type'=>'number','min'=>'0'],
  'GolosContra'=>['label'=>'Golos contra','type'=>'number','min'=>'0'],
  'GolosIntervaloFavor'=>['label'=>'Intervalo — a favor','type'=>'number','min'=>'0'],
  'GolosIntervaloContra'=>['label'=>'Intervalo — contra','type'=>'number','min'=>'0'],
  'EstadoJogo'=>['label'=>'Estado','type'=>'select','options'=>['Agendado','Realizado','Adiado','Cancelado'],'required'=>true,'default'=>'Agendado'],
  'CasaFora'=>['label'=>'Casa / Fora','type'=>'select','options'=>['Casa','Fora'],'required'=>true,'default'=>'Casa'],
  'Observacoes'=>['label'=>'Observações','type'=>'textarea','full'=>true],
 ]],
'treinos'=>[
 'table'=>'treinos','pk'=>'IdTreino','title'=>'Treinos','singular'=>'treino','subtitle'=>'Planeamento de sessões, objetivos e controlo de assiduidade.',
 'filters'=>['IdEquipa','DataTreino','TipoTreino','Local'],
 'fields'=>[
  'IdEquipa'=>['label'=>'Equipa','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','required'=>true],
  'DataTreino'=>['label'=>'Data','type'=>'date','required'=>true],
  'HoraInicio'=>['label'=>'Início','type'=>'time'],
  'HoraFim'=>['label'=>'Fim','type'=>'time'],
  'Local'=>['label'=>'Local','type'=>'text','search'=>true],
  'TipoTreino'=>['label'=>'Tipo','type'=>'select','options'=>['Fisico','Tecnico','Tatico','Recuperacao','Jogo Treino','Video/Analise'],'required'=>true],
  'Descricao'=>['label'=>'Objetivos / descrição','type'=>'textarea','full'=>true],
 ]],
'lesoes'=>[
 'table'=>'lesoes','pk'=>'IdLesao','title'=>'Lesões','singular'=>'lesão','subtitle'=>'Indisponibilidades, evolução, recuperação e regresso à competição.',
 'filters'=>['IdAtleta','DataInicio','Gravidade','Estado'],
 'fields'=>[
  'IdAtleta'=>['label'=>'Atleta','type'=>'relation','table'=>'atletas','pk'=>'IdAtleta','display'=>'Nome','required'=>true],
  'DataInicio'=>['label'=>'Data de início','type'=>'date','required'=>true],
  'TipoLesao'=>['label'=>'Tipo de lesão','type'=>'text','required'=>true,'search'=>true],
  'Descricao'=>['label'=>'Descrição / plano','type'=>'textarea','full'=>true],
  'Gravidade'=>['label'=>'Gravidade','type'=>'select','options'=>['Ligeira','Moderada','Grave']],
  'DataPrevistaRegresso'=>['label'=>'Regresso previsto','type'=>'date'],
  'DataRegresso'=>['label'=>'Regresso efetivo','type'=>'date'],
  'Estado'=>['label'=>'Estado','type'=>'select','options'=>['Em Recuperacao','Recuperado','Indisponivel'],'required'=>true,'default'=>'Em Recuperacao'],
 ]],
'participacoes'=>[
 'table'=>'competicoes_equipas','pk'=>'IdCompeticaoEquipa','title'=>'Participações','singular'=>'participação','subtitle'=>'Equipas inscritas em cada competição, grupo e estado.',
 'filters'=>['IdCompeticao','IdEquipa','Estado','Grupo'],
 'fields'=>[
  'IdCompeticao'=>['label'=>'Competição','type'=>'relation','table'=>'competicoes','pk'=>'IdCompeticao','display'=>'NomeCompeticao','required'=>true],
  'IdEquipa'=>['label'=>'Equipa','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','required'=>true],
  'Estado'=>['label'=>'Estado','type'=>'select','options'=>['Ativa','Eliminada','Desistiu'],'required'=>true,'default'=>'Ativa'],
  'Grupo'=>['label'=>'Grupo / série','type'=>'text','search'=>true],
 ]],
'classificacoes'=>[
 'table'=>'classificacao_competicao','pk'=>'IdClassificacao','title'=>'Classificações','singular'=>'linha da classificação','subtitle'=>'Tabela classificativa de referência por competição.',
 'filters'=>['IdCompeticao','IdEquipa'],
 'fields'=>[
  'IdCompeticao'=>['label'=>'Competição','type'=>'relation','table'=>'competicoes','pk'=>'IdCompeticao','display'=>'NomeCompeticao','required'=>true],
  'IdEquipa'=>['label'=>'Equipa','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','required'=>true],
  'Posicao'=>['label'=>'Posição','type'=>'number','min'=>'1'],
  'Jogos'=>['label'=>'J','type'=>'number','min'=>'0','default'=>'0'],
  'Vitorias'=>['label'=>'V','type'=>'number','min'=>'0','default'=>'0'],
  'Empates'=>['label'=>'E','type'=>'number','min'=>'0','default'=>'0'],
  'Derrotas'=>['label'=>'D','type'=>'number','min'=>'0','default'=>'0'],
  'GolosMarcados'=>['label'=>'GM','type'=>'number','min'=>'0','default'=>'0'],
  'GolosSofridos'=>['label'=>'GS','type'=>'number','min'=>'0','default'=>'0'],
  'DiferencaGolos'=>['label'=>'DG','type'=>'number','default'=>'0'],
  'Pontos'=>['label'=>'Pontos','type'=>'number','default'=>'0'],
  'AtualizadoEm'=>['label'=>'Atualizado em','type'=>'datetime-local'],
  'Fonte'=>['label'=>'Fonte','type'=>'url'],
 ]],
'utilizadores'=>[
 'table'=>'utilizadores','pk'=>'IdUtilizador','title'=>'Utilizadores','singular'=>'utilizador','subtitle'=>'Contas, perfis, estado e controlo de acesso à aplicação.',
 'filters'=>['Nome','Email','TipoUtilizador','Estado'],
 'fields'=>[
  'Nome'=>['label'=>'Nome','type'=>'text','required'=>true,'search'=>true],
  'Email'=>['label'=>'Email','type'=>'email','required'=>true,'search'=>true],
  'Password'=>['label'=>'Password','type'=>'password','secret'=>true],
  'TipoUtilizador'=>['label'=>'Perfil','type'=>'select','options'=>['Administrador','Treinador','Dirigente','Atleta'],'required'=>true],
  'IdAtleta'=>['label'=>'Atleta associado','type'=>'relation','table'=>'atletas','pk'=>'IdAtleta','display'=>'Nome','nullable'=>true],
  'IdEquipa'=>['label'=>'Equipa associada','type'=>'relation','table'=>'equipas','pk'=>'IdEquipa','display'=>'NomeEquipa','nullable'=>true],
  'Estado'=>['label'=>'Estado','type'=>'select','options'=>['Ativo','Inativo'],'required'=>true,'default'=>'Ativo'],
 ]],
];
